### ISSUE TITLE
NullPointer when trying to equip before unequipping.

### ISSUE THREAD

**Issue by CalebCrosbySears** [aknobloch/An-Endless-Night#44]
Exception in thread "Thread-15" java.lang.NullPointerException
	at main.MenuSystem.InventoryMenu.unEquipItem(InventoryMenu.java:92)
	at main.MenuSystem.InventoryMenu.mainPrompt(InventoryMenu.java:200)
	at main.MenuSystem.MenuLoader$4.run(MenuLoader.java:174)
	at java.lang.Thread.run(Thread.java:745)

**Comment by aknobloch** [comment]
@Jory1110 did you say you fixed this one?

**Comment by Jory1110** [comment]
Fixed.



Sent from my Sprint Samsung Galaxy Note5.


-------- Original message --------
